[package]
name = "soul"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
colored_truecolor = "0.1.0"
indicatif = "0.17.11"
tokio = { version = "1.44.1", features = ["full"] }
